/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import java.awt.CardLayout;

/**
 *
 * @author GVXTR
 */
public class Principal extends javax.swing.JFrame {

    CardLayout cardLayout;

    public Principal() {
        initComponents();
        cardLayout = (CardLayout) (PnlCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PnlAccion = new javax.swing.JPanel();
        btnOperaciones = new javax.swing.JLabel();
        btnConsultas = new javax.swing.JLabel();
        PnlCards = new javax.swing.JPanel();
        CardOperaciones = new javax.swing.JPanel();
        btnOVentas = new javax.swing.JLabel();
        btnOClientes = new javax.swing.JLabel();
        btnOProveedores = new javax.swing.JLabel();
        btnOProductos = new javax.swing.JLabel();
        OpTexto = new javax.swing.JLabel();
        CardConsultas = new javax.swing.JPanel();
        btnCVentas = new javax.swing.JLabel();
        btnCProveedores = new javax.swing.JLabel();
        btnCProductos = new javax.swing.JLabel();
        OpTexto1 = new javax.swing.JLabel();
        btnCClientes1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        PnlAccion.setBackground(new java.awt.Color(33, 150, 243));

        btnOperaciones.setBackground(new java.awt.Color(66, 165, 245));
        btnOperaciones.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnOperaciones.setForeground(new java.awt.Color(224, 224, 224));
        btnOperaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/operaciones.png"))); // NOI18N
        btnOperaciones.setText("Operaciones");
        btnOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOperacionesMouseClicked(evt);
            }
        });

        btnConsultas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(224, 224, 224));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas1.png"))); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PnlAccionLayout = new javax.swing.GroupLayout(PnlAccion);
        PnlAccion.setLayout(PnlAccionLayout);
        PnlAccionLayout.setHorizontalGroup(
            PnlAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAccionLayout.createSequentialGroup()
                .addComponent(btnOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 732, Short.MAX_VALUE))
        );
        PnlAccionLayout.setVerticalGroup(
            PnlAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSplitPane1.setTopComponent(PnlAccion);

        PnlCards.setLayout(new java.awt.CardLayout());

        btnOVentas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnOVentas.setForeground(new java.awt.Color(76, 81, 81));
        btnOVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        btnOVentas.setText("Ventas");
        btnOVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOVentasMouseClicked(evt);
            }
        });

        btnOClientes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnOClientes.setForeground(new java.awt.Color(76, 81, 81));
        btnOClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        btnOClientes.setText("Clientes");
        btnOClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOClientesMouseClicked(evt);
            }
        });

        btnOProveedores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnOProveedores.setForeground(new java.awt.Color(76, 81, 81));
        btnOProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        btnOProveedores.setText("Proveedores");
        btnOProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOProveedoresMouseClicked(evt);
            }
        });

        btnOProductos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnOProductos.setForeground(new java.awt.Color(76, 81, 81));
        btnOProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        btnOProductos.setText("Productos");
        btnOProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOProductosMouseClicked(evt);
            }
        });

        OpTexto.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        OpTexto.setForeground(new java.awt.Color(76, 81, 81));
        OpTexto.setText("OPERACIONES");
        OpTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpTextoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CardOperacionesLayout = new javax.swing.GroupLayout(CardOperaciones);
        CardOperaciones.setLayout(CardOperacionesLayout);
        CardOperacionesLayout.setHorizontalGroup(
            CardOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardOperacionesLayout.createSequentialGroup()
                .addGroup(CardOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardOperacionesLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(OpTexto))
                    .addGroup(CardOperacionesLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnOVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnOProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        CardOperacionesLayout.setVerticalGroup(
            CardOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardOperacionesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(OpTexto)
                .addGap(92, 92, 92)
                .addGroup(CardOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        PnlCards.add(CardOperaciones, "CardOperaciones");

        btnCVentas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCVentas.setForeground(new java.awt.Color(76, 81, 81));
        btnCVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        btnCVentas.setText("Ventas");
        btnCVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCVentasMouseClicked(evt);
            }
        });

        btnCProveedores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCProveedores.setForeground(new java.awt.Color(76, 81, 81));
        btnCProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        btnCProveedores.setText("Proveedores");
        btnCProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCProveedoresMouseClicked(evt);
            }
        });

        btnCProductos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCProductos.setForeground(new java.awt.Color(76, 81, 81));
        btnCProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/productos.png"))); // NOI18N
        btnCProductos.setText("Productos");
        btnCProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCProductosMouseClicked(evt);
            }
        });

        OpTexto1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        OpTexto1.setForeground(new java.awt.Color(76, 81, 81));
        OpTexto1.setText("CONSULTAS");
        OpTexto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpTexto1MouseClicked(evt);
            }
        });

        btnCClientes1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCClientes1.setForeground(new java.awt.Color(76, 81, 81));
        btnCClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        btnCClientes1.setText("Clientes");
        btnCClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCClientes1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CardConsultasLayout = new javax.swing.GroupLayout(CardConsultas);
        CardConsultas.setLayout(CardConsultasLayout);
        CardConsultasLayout.setHorizontalGroup(
            CardConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardConsultasLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(CardConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardConsultasLayout.createSequentialGroup()
                        .addComponent(OpTexto1)
                        .addGap(388, 388, 388))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardConsultasLayout.createSequentialGroup()
                        .addComponent(btnCVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnCProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        CardConsultasLayout.setVerticalGroup(
            CardConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardConsultasLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(OpTexto1)
                .addGap(82, 82, 82)
                .addGroup(CardConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        PnlCards.add(CardConsultas, "CardConsultas");

        jSplitPane1.setRightComponent(PnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOperacionesMouseClicked
        cardLayout.show(PnlCards, "CardOperaciones");
    }//GEN-LAST:event_btnOperacionesMouseClicked

    private void btnConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasMouseClicked
        cardLayout.show(PnlCards, "CardConsultas");
    }//GEN-LAST:event_btnConsultasMouseClicked

    private void btnOVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOVentasMouseClicked
        OpVentas go = new OpVentas();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOVentasMouseClicked

    private void btnOClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOClientesMouseClicked
        OpClientes go = new OpClientes();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOClientesMouseClicked

    private void btnOProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOProveedoresMouseClicked
        OpProveedores go = new OpProveedores();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOProveedoresMouseClicked

    private void btnOProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOProductosMouseClicked
        OpProductos go = new OpProductos();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOProductosMouseClicked

    private void btnCVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCVentasMouseClicked
        ConVentas go = new ConVentas();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCVentasMouseClicked

    private void OpTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpTextoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OpTextoMouseClicked

    private void OpTexto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpTexto1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OpTexto1MouseClicked

    private void btnCClientes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCClientes1MouseClicked
        ConClientes go = new ConClientes();
        go.setVisible(true);
    }//GEN-LAST:event_btnCClientes1MouseClicked

    private void btnCProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCProductosMouseClicked
        ConProductos go = new ConProductos();
        go.setVisible(true);
    }//GEN-LAST:event_btnCProductosMouseClicked

    private void btnCProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCProveedoresMouseClicked
        ConProveedores go = new ConProveedores();
        go.setVisible(true);
    }//GEN-LAST:event_btnCProveedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardConsultas;
    private javax.swing.JPanel CardOperaciones;
    private javax.swing.JLabel OpTexto;
    private javax.swing.JLabel OpTexto1;
    private javax.swing.JPanel PnlAccion;
    private javax.swing.JPanel PnlCards;
    private javax.swing.JLabel btnCClientes1;
    private javax.swing.JLabel btnCProductos;
    private javax.swing.JLabel btnCProveedores;
    private javax.swing.JLabel btnCVentas;
    private javax.swing.JLabel btnConsultas;
    private javax.swing.JLabel btnOClientes;
    private javax.swing.JLabel btnOProductos;
    private javax.swing.JLabel btnOProveedores;
    private javax.swing.JLabel btnOVentas;
    private javax.swing.JLabel btnOperaciones;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
